### ISSUE TITLE
Add CFF files in all API repositories

### ISSUE THREAD

**Issue by MansMeg** [swerik-project/the-swedish-parliament-corpus#1]
We should add a citation file to all our data repositories. This will fulfill two purposes:
1. It will simplify the citations for users (so they can get one bibtex quickly per repo they use)
2. It can work as a tom.xml file for the repository, ie the R package can check which repo it is by looking at the CFF file.

Here is more information:
https://citation-file-format.github.io/

I'm thinking of us requiring (using a unit test) that all repos has an identifier to the repo as:
```
identifiers:
  - description: "The main repository URL"
    type: url
    value: "https://github.com/swerik-project/riksdag-records"
```
Then, we can all use this id in the CFF to check the repository. E.g. I need to use this in the R package. Even better would be something like:
```
identifiers:
  - description: "repository"
    type: id
    value: "riksdag-records"
```
but that is not supported by the CFF format.

Any thoughts on this @ninpnin or @BobBorges ?

**Comment by BobBorges** [comment]
I think we should also look into generating a DOI for every release (perhaps only major versions(?) -- to be discussed), whether via zenodo or some other service. 

Could you then use the  DOI of the most recent version of whatever repo as the ID in your r package without adding extra fields to .cff specification?

**Comment by MansMeg** [comment]
I think I need something that just says what repo it is, i.e. Is it riksdagen-records, riksdagen-interpellations, etc? I think the DOI is a good idea for major releases anyway, but that will not solve this problem.

**Comment by BobBorges** [comment]
You could use:
```
identifiers:
  - description: "repository"
    type: other
    value: "riksdag-records"
```
The `other` is a bit lame, but it would serve the purpose.

**Comment by BobBorges** [comment]
Who should the authors of the corpus be? Same as the LREC paper?

**Comment by MansMeg** [comment]
I think we should point to the LREC paper both for the records and person datasets.

**Comment by BobBorges** [comment]
The question came up this morning about citing the paper vs citing the dataset in the repo / software in the repo, and I think after looking at the cff documentation more carefully that the cff files are meant to cite the data/software, and actually there is not even a key within the schema to cite descriptions of the resource (like our LREC paper). I would make the cff files following the example below, and when the paper is published, we can archive it and either point to it in the readme or include it in a 'publications' or similar zip with dated releases on the landing page.

```
cff-version: 1.2.0
message: To cite this reposository, please use these metadata.
title: The Swedish Parliament Corpus: Riksdagen Records
version: v1.0.0
authors:
  - given-names: Väinö 
    family-names: Yrjänäinen
    orcid: "https://orcid.org/1111-2222-3333-4444"
    alias: ninpnin
  - given-names: Fredrik 
    family-names: Mohammadi Norén
    orcid: "https://orcid.org/1111-2222-3333-4444"
    alias: fredrik1984
  - family-names: Borges
    given-names: Robert
    orcid: "https://orcid.org/0000-0002-7647-4048"
    alias: BobBorges
  - given-names: Johan 
    family-names: Jarlbrink
    orcid: "https://orcid.org/1111-2222-3333-4444"
    alias: JoJanotrealalais
  - given-names: Lotta 
    family-names: Åberg Brorsson
    orcid: "https://orcid.org/1111-2222-3333-4444"
    alias: Lottabrorson
  - given-names: Anders P. 
    family-names: Olsson
    orcid: "https://orcid.org/1111-2222-3333-4444"
    alias: AnOlnotrealalias
  - given-names: Pelle 
    family-names: Snickars
    orcid: "https://orcid.org/1111-2222-3333-4444"
    alias: PeSnnotrealalias
  - given-names: Måns 
    family-names: Magnusson
    orcid: "https://orcid.org/1111-2222-3333-4444"
    alias: MansMeg
date-released: 2024-04-17
identifiers:
  - description: This is just the repository basename; we need it for the R package.
    type: other
    value: riksdagen-records
  - description: DOI of each release. We should archive releases with a doi as part of the workflow.
    type: DOI
    value: 01.xxx/zenodo.yyyyy
license: MIT
repository-code: "https://github.com/swerik-project/"
url: "https://github.com/swerik-project/the-swedish-parliament-corpus"
type: dataset
```
